[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fact_gpt_solana = "EciTmTmvfdp8rcJurZ43r7thhnvhZPfA3ChJ8nuYqsC1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shayan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
